<?php

namespace ContainerOO6B9L5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserControllerinsertUserService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.r_XOrDH.App\Controller\Guest\UserController::insertUser()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.r_XOrDH.App\\Controller\\Guest\\UserController::insertUser()'] = ($container->privates['.service_locator.r_XOrDH'] ?? $container->load('get_ServiceLocator_RXOrDHService'))->withContext('App\\Controller\\Guest\\UserController::insertUser()', $container);
    }
}
