<?php

namespace ContainerOtACIYb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_6DAeVjeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.6DAeVje' shared service.
     *
     * @return \App\Controller\Admin\Request
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\Admin\\AdminBookController::insertAdminBook()": the $request argument is type-hinted with the non-existent class or interface: "App\\Controller\\Admin\\Request". Did you forget to add a use statement?');
    }
}
