<?php

namespace ContainerOtACIYb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminUserControllerinsertAdminUserService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.r_XOrDH.App\Controller\Admin\AdminUserController::insertAdminUser()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.r_XOrDH'] ?? $container->load('get_ServiceLocator_RXOrDHService'));

        if (isset($container->privates['.service_locator.r_XOrDH.App\\Controller\\Admin\\AdminUserController::insertAdminUser()'])) {
            return $container->privates['.service_locator.r_XOrDH.App\\Controller\\Admin\\AdminUserController::insertAdminUser()'];
        }

        return $container->privates['.service_locator.r_XOrDH.App\\Controller\\Admin\\AdminUserController::insertAdminUser()'] = $a->withContext('App\\Controller\\Admin\\AdminUserController::insertAdminUser()', $container);
    }
}
