<?php

namespace ContainerOtACIYb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminBookControllerinsertAdminBookService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.NnSVbJt.App\Controller\Admin\AdminBookController::insertAdminBook()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.NnSVbJt.App\\Controller\\Admin\\AdminBookController::insertAdminBook()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'request' => ['privates', '.errored.6DAeVje', NULL, 'Cannot determine controller argument for "App\\Controller\\Admin\\AdminBookController::insertAdminBook()": the $request argument is type-hinted with the non-existent class or interface: "App\\Controller\\Admin\\Request". Did you forget to add a use statement?'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'request' => '?',
            'entityManager' => '?',
        ]))->withContext('App\\Controller\\Admin\\AdminBookController::insertAdminBook()', $container);
    }
}
