<?php

namespace ContainerOtACIYb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArticlesControllershowCategoryByIdService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.MEncpnc.App\Controller\Guest\ArticlesController::showCategoryById()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.MEncpnc.App\\Controller\\Guest\\ArticlesController::showCategoryById()'] = ($container->privates['.service_locator.MEncpnc'] ?? $container->load('get_ServiceLocator_MEncpncService'))->withContext('App\\Controller\\Guest\\ArticlesController::showCategoryById()', $container);
    }
}
