<?php

namespace ContainerOtACIYb;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReviewControllerinsertReviewService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.WrRCf2S.App\Controller\Guest\ReviewController::insertReview()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.WrRCf2S.App\\Controller\\Guest\\ReviewController::insertReview()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
            'bookRepository' => ['privates', 'App\\Repository\\BookRepository', 'getBookRepositoryService', true],
        ], [
            'entityManager' => '?',
            'userRepository' => 'App\\Repository\\UserRepository',
            'bookRepository' => 'App\\Repository\\BookRepository',
        ]))->withContext('App\\Controller\\Guest\\ReviewController::insertReview()', $container);
    }
}
