<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOO6B9L5\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOO6B9L5/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOO6B9L5.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOO6B9L5\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOO6B9L5\App_KernelDevDebugContainer([
    'container.build_hash' => 'OO6B9L5',
    'container.build_id' => '33f250af',
    'container.build_time' => 1723548246,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOO6B9L5');
